name: Fetch zotero bibliography
on:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches:
      - main

jobs:
  fetch_zotero_bibliography:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm --prefix fetch-zotero ci
      - run: npm --prefix fetch-zotero run start
        env:
          BIBTEX_PATH: "${{ github.workspace }}/joannajasinska-lib.bib"
          ZOTEROJSON_PATH: "${{ github.workspace }}/joannajasinska-lib.zotero.json"
          ZOTERO_USERID: "6109417"
          ZOTERO_APIKEY: "${{ secrets.ZOTERO_APIKEY }}"
      - run: ls -a
      - run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'fetch-zotero.yml (Joanna Jasińska)'
            git config --global user.email 'joannajasinska@users.noreply.github.com'
            git add joannajasinska-lib.bib joannajasinska-lib.zotero.json
            git commit -m "sync: bibliography"
            git push origin main
          else
            echo "No changes"
          fi
